name: Python_Web_Development
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - python-dotenv
  - pydantic
  - sqlalchemy        # DB ORM을 위한 패키지
#  - pydantic-settings # 설정 관리를 위한 패키지
#  - python-jose      # JWT 토큰 생성 및 검증
#  - passlib         # 비밀번호 해싱
#  - bcrypt          # 비밀번호 암호화 알고리즘
#  - python-multipart # form-data 처리
#  - email-validator # 이메일 유효성 검사
#pip:
#  - python-jose[cryptography]  # JWT 암호화를 위한 추가 기능



# 환경 생성

# conda env create -f environment.yml

# conda env update -f environment.yml
# 개별 패키지 설치
# conda install -c conda-forge python-dotenv pyyaml

# conda activate Python_Web_Development

# conda deactivate

# conda env list

# conda env remove -n Python_Web_Development

# conda config --show envs_dirs

# python --version
