name: Python_Web_Development
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - fastapi>=0.100.0 # pydantic 2.0.0 이상 버전을 사용하기 위해 fastapi 0.100.0 이상 버전을 사용
  - uvicorn
  - python-dotenv
  - pydantic>=2.0.0 # pydantic 2.0.0 이상 버전을 사용하기 위해 fastapi 0.100.0 이상 버전을 사용
  - sqlalchemy        # DB ORM을 위한 패키지
  - python-jose      # JWT 토큰 생성 및 검증
#  - pydantic-settings # 설정 관리를 위한 패키지
  - passlib         # 비밀번호 해싱 (bcrypt 와 함께 사용)
  - bcrypt          # 비밀번호 암호화 알고리즘 (passlib 와 함께 사용)
  - email-validator
  - python-multipart
#  - python-multipart # form-data 처리
#  - email-validator # 이메일 유효성 검사
#pip:
#  - python-jose[cryptography]  # JWT 암호화를 위한 추가 기능



# 환경 생성

# taskkill /F /IM python.exe

# uvicorn main:app --reload

# conda env create -f environment.yml

# conda env update -f environment.yml
# 개별 패키지 설치
# conda install -c conda-forge python-dotenv pyyaml

# conda activate Python_Web_Development

# conda deactivate

# conda env list

# 패키지 버전 확인
# conda list
# 특정 패키지 버전 확인
# conda list pydantic
# conda list fastapi

# 현재 환경 전체 의존성 트리 확인
# conda list --explicit

# conda env remove -n Python_Web_Development

# conda config --show envs_dirs

# python --version
